from __future__ import annotations

print("=" * 60)
print("     AUTOMATION GENERATOR TEST SUITE")
print("=" * 60)

from automation.ai.execution_plan import (
    ExecutionPlan,
)

from automation.ai.plan_step import (
    PlanStep,
)

from automation.ai.automation_generator import (
    AutomationGenerator,
)

from automation.automation_runtime import (
    AutomationRuntime,
)

# ==================================================

generator = AutomationGenerator()

runtime = AutomationRuntime()

runtime.start()

# ==================================================
# Create Plan
# ==================================================

plan = ExecutionPlan(

    name="Night Backup",

    description="Generated by Planner",

)

# Trigger

trigger = PlanStep(
    "Create Trigger"
)

trigger.set_parameter(
    "trigger",
    "time",
)

trigger.set_parameter(
    "schedule",
    "every night",
)

plan.add_step(
    trigger
)

# Action

action = PlanStep(
    "Create Action"
)

action.set_parameter(
    "action",
    "backup",
)

action.set_parameter(
    "target",
    "downloads",
)

plan.add_step(
    action
)

# Register

plan.add_step(

    PlanStep(
        "Register Automation"
    )

)

# ==================================================
# Generator
# ==================================================

print()

print("Generating Automation...")

automation = generator.generate(
    plan
)

assert automation.name == "Night Backup"

assert (
    automation.trigger["type"]
    == "time"
)

assert (
    automation.trigger["schedule"]
    == "every night"
)

assert (
    automation.action["type"]
    == "backup"
)

assert (
    automation.action["target"]
    == "downloads"
)

print("PASS")

# ==================================================
# Runtime
# ==================================================

print()

print("Registering Runtime...")

runtime.register_automation(
    automation
)

assert (
    runtime.automation_count()
    == 1
)

print("PASS")

# ==================================================

print()

print("Automation")

print(
    automation
)

print()

print("Trigger")

print(
    automation.trigger
)

print()

print("Action")

print(
    automation.action
)

print()

print("Metadata")

print(
    automation.metadata
)

print()

print(
    "Automation Count:",
    runtime.automation_count(),
)

runtime.stop()

print()

print("=" * 60)

print(
    "AUTOMATION GENERATOR TEST SUITE PASSED"
)

print("=" * 60)
