from __future__ import annotations

from automation.ai.execution_plan import (
    ExecutionPlan,
)

from automation.ai.intent import (
    Intent,
)

from automation.ai.intent_types import (
    IntentType,
)

from automation.ai.plan_step import (
    PlanStep,
)


class Planner:
    """
    Converts an Intent into
    an ExecutionPlan.
    """

    def create_plan(
        self,
        intent: Intent,
    ) -> ExecutionPlan:

        plan = ExecutionPlan(

            name=intent.intent_type.value,

            description="Generated by Planner",

        )

        # ------------------------------------
        # CREATE AUTOMATION
        # ------------------------------------

        if (
            intent.intent_type
            == IntentType.CREATE_AUTOMATION
        ):

            self._create_automation_plan(
                plan,
                intent,
            )

        # ------------------------------------

        elif (
            intent.intent_type
            == IntentType.RUN_AUTOMATION
        ):

            self._run_plan(
                plan,
                intent,
            )

        # ------------------------------------

        elif (
            intent.intent_type
            == IntentType.STOP_AUTOMATION
        ):

            self._stop_plan(
                plan,
                intent,
            )

        # ------------------------------------

        elif (
            intent.intent_type
            == IntentType.QUESTION
        ):

            plan.add_step(

                PlanStep(

                    name="Answer Question",

                    description="Generate response",

                )

            )

        # ------------------------------------

        else:

            plan.add_step(

                PlanStep(

                    name="Unknown Intent",

                    description="No execution available",

                )

            )

        return plan

    # ========================================

    def _create_automation_plan(
        self,
        plan,
        intent,
    ):

        plan.add_step(

            PlanStep(

                "Validate Intent",

            )

        )

        plan.add_step(

            PlanStep(

                "Create Trigger",

                parameters={

                    "trigger":
                    intent.get_parameter(
                        "trigger"
                    ),

                },

            )

        )

        plan.add_step(

            PlanStep(

                "Create Action",

                parameters={

                    "action":
                    intent.get_parameter(
                        "action"
                    ),

                },

            )

        )

        plan.add_step(

            PlanStep(

                "Register Automation",

            )

        )

    # ========================================

    def _run_plan(
        self,
        plan,
        intent,
    ):

        plan.add_step(

            PlanStep(

                "Run Automation",

            )

        )

    # ========================================

    def _stop_plan(
        self,
        plan,
        intent,
    ):

        plan.add_step(

            PlanStep(

                "Stop Automation",

            )

        )

    # ========================================

    def __repr__(self):

        return "<Planner>"
