from __future__ import annotations

from automation.ai.ai_brain import AIBrain
from automation.ai.llm.ollama_adapter import OllamaAdapter
from automation.ai.tools.shell_tool import ShellTool
from automation.voice.voice_output import VoiceOutput


class Assistant:

    def __init__(self):

        self.voice = VoiceOutput()

        self.brain = AIBrain(
            llm=OllamaAdapter(
                model="qwen2.5:7b"
            )
        )

        # Register available tools
        self.brain.register_tool(
            ShellTool()
        )

    def handle(self, text: str):

        print("\nUSER :", text)

        if not text.strip():
            return None

        try:

            response = self.brain.ask(
                text
            )

            if not response.success:

                msg = "Sorry, I could not process that request."

                print("❌", msg)

                self.voice.speak(msg)

                return None

            # Final answer generated by LLM
            answer = response.get_metadata(
                "final_answer"
            )

            if not answer:

                answer = response.content

            if not answer:

                msg = "I could not generate a response."

                print("❌", msg)

                self.voice.speak(msg)

                return None

            print("🤖 Assistant :", answer)

            self.voice.speak(
                answer
            )

            return answer

        except Exception as error:

            print(
                "❌ Assistant Error:",
                error
            )

            msg = "Sorry, something went wrong."

            self.voice.speak(
                msg
            )

            return None

    def __repr__(self):

        return "<Assistant>"